name: Get Activation File
on: workflow_dispatch
jobs:
  activation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Manual Activation File
        run: |
          echo "Membuat file manual..."
          touch manual.alf
          # File ini hanya sebagai pancingan untuk melihat environment
      
      - name: Request License File
        uses: game-ci/unity-request-activation-file@v2
        # Kita tetap coba v2 tapi dengan bypass
